name: Reject Direct Push
on:
  push:
    branches: [main]
jobs:
  reject:
    runs-on: ubuntu-latest
    steps:
      - name: Fail if direct push
        run: |
          echo "Direct push to main is not allowed."
          exit 1
